### PR TITLE
Exploratory refactoring of libzim

### PR DESCRIPTION
**Pull request by veloman-yunkan**
This PR contains some primitive improvements made to the libzim source code while studying it in the context of https://github.com/openzim/libzim/projects/2.

### CODE REVIEW

**Comment by mgautierfr** [comment]
What is the status of this PR ?
Do you plan to merge it ?
It is pretty long (21 commits), if you plan to merge those commits in master, it would be nice to split this PR in several others, regrouping commits by file (dirent, buffer, ...) or thematic (constructor, memory management, ...)

**Comment by veloman-yunkan** [comment]
@mgautierfr What will splitting this PR buy us? It is just a set of independent clean-up changes almost without any impact on functionality (with the exception of minor bug-fixes in certain corner cases).
I can publish this PR in its entirety now, and continue similar activity in a new PR.

**Comment by mgautierfr** [comment]
Reviewing a long PR is pretty ... long (and complex).
Even reviewing commit by commit.
If one or two points have to be discuss, the whole PR is stuck. All other commits could be merged but they are not. If you change the few incriminated commits, the reviewer have to "filter" to not review again "accepted" changes. And you may have conflicts appearing between commits if you change one.
Not even speaking about the fact that you will continue work on the project, probably base on the change you've just made, not `master`. Other dev will do the same, increasing the chance of conflict between branches.

**Comment by veloman-yunkan** [comment]
I moved the commits related to `src/buffer.{h,cpp}` into a separate PR #383, which makes this PR reasonably small (though not well-focused on any one topic).

**Comment by mgautierfr** [comment]
Nothing to say.
Nice improvement and cleanup of the code.

**Pull request merged**
