### PR TITLE
Add code coverage and upload it to codecov.

### LINKED ISSUE #234: Introduce code coverage with codecov
kiwix-android can be taken as example

### PR DESCRIPTION
**Pull request by mgautierfr**
Fix #234

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr nice, even if the code coverage overall percentage is not fantastic (but this is not a surprise).

**Comment by kelson42** [comment]
@mgautierfr Could  we add something like [this](https://github.com/openzim/mwoffliner/blob/master/.codecov.yml). This would secure that the code-coverage never goes backward in the future because of new PR. In other words: that any new code comes with corresponding unit tests.

**Comment by mgautierfr** [comment]
Definitively yes but not sure about the one you've linked.
From what I understand from https://docs.codecov.io/docs/commit-status, with the mwoffliner's `.codecov.yml` your are allowing the patched line to be less tested (-0.1%).

**Comment by kelson42** [comment]
@mgautierfr Yes, there is a small tolerance.

**Pull request merged**
