### PR TITLE
Updated AUTHORS file

### PR DESCRIPTION
**Pull request by kelson42**
I have kept only the most significant contributors

### CODE REVIEW

**Comment by kelson42** [comment]
@data-man You were indeed on the edge ;)

**Comment by data-man** [comment]
I propose add links to GutHub profiles (if exists).

> You were indeed on the edge ;)

I have big plans (secret!) for libzim, so... :)

**Comment by mgautierfr** [comment]
> I propose add links to GutHub profiles (if exists).

I agree (but keep the mail anyway)

**Comment by kelson42** [comment]
@mgautierfr @data-man How do you want to do that? Which format are you exactly following, because this is a Google recommended format

**Pull request merged**
