### PR TITLE
Diacritics insensitive suggestions

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Fixes kiwix/libkiwix#758

### CODE REVIEW

**Comment by veloman-yunkan** [comment]
CI fails because `removeAccents()` is only enabled in a Xapian-enabled configuration. Can we change that?

**Comment by mgautierfr** [comment]
> CI fails because removeAccents() is only enabled in a Xapian-enabled configuration. Can we change that?

We could but it is not straitforward. `removeAccents` depends on icu. But we are (were) using icu on the search/indexation part (so with xapian)
I think it would be better to remove accents only when we do a xapian search (ie in `getEnquire`)
We would not remove accents for the fallback suggestion system base on the titles list in zim file but it would not work anyway if we remove the accents as we are doing a binary search on the utf8 representation a the titles.

**Comment by veloman-yunkan** [comment]
> 



> 

Makes sense. Done.

**Review by mgautierfr — APPROVED** [review]
LGTM

**Pull request merged**
