### PR TITLE
Add M1/macOS14 to Apple CI

### PR DESCRIPTION
**Pull request by kelson42**

### CODE REVIEW

**Comment by mgautierfr** [comment]
> @mgautierfr why the CI fails? Something missing in the deps?

As the log says:
```
 ld: warning: ignoring file '/Users/runner/BUILD_native_dyn/INSTALL/lib/liblzma.5.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/runner/BUILD_native_dyn/INSTALL/lib/libzstd.1.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/runner/BUILD_native_dyn/INSTALL/lib/libxapian.30.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/runner/BUILD_native_dyn/INSTALL/lib/libicui18n.73.2.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/runner/BUILD_native_dyn/INSTALL/lib/libicuuc.73.2.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/runner/BUILD_native_dyn/INSTALL/lib/libicudata.73.2.dylib': found architecture 'x86_64', required architecture 'arm64'
```

This is because os name `macos` is the same for `macos-13` and `macos-14` and they are not the same architecture. (Without speaking that kiwix-build is not running on `macos-14`)

**Comment by kelson42** [comment]
> This is because os name `macos` is the same for `macos-13` and `macos-14` and they are not the same architecture. (Without speaking that kiwix-build is not running on `macos-14`)

Thx, so if I get it right a victim of this implicit, unclear, context dependent fake target `native_xyz`?

**Comment by kelson42** [comment]
@mgautierfr Now, the targets have proper clear name (I believe so at least) but seems the data have to be generated with proper name somewhere else, I guess in kiwix-build!

**Comment by kelson42** [comment]
@mgautierfr What should we do with this PR now?

**Comment by mgautierfr** [comment]
With last update on kiwix-build side, we can now compile on M1/MacOS14 (aarch64) with the dependencies build by kiwix-build (cross-compiled from x86_64(macos13) to aarch64).

**Pull request merged**
