### PR TITLE
fix ubuntu-noble package step

### PR DESCRIPTION
**Pull request by tusharpm**
- remove missing ppa

### CODE REVIEW

**Comment by kelson42** [comment]
@tusharpm Thank you for completing #816

**Comment by tusharpm** [comment]
If you're okay with experimentation, I think the PPAs can be removed from the other Ubuntu builds as well. I'm happy to PR the commit to try it out.

**Comment by kelson42** [comment]
@tusharpm If you want to help, what is very welcome, would be great to adapt CI/CD for openzim/zim-tools, kiwix/libkiwix, kiwix-kiwix-tools and kiwix/kiwix-desktop the same way.

**Comment by tusharpm** [comment]
The other CI builds should start succeeding now that the PPA has noble packages published. I'll take a look again at the next actions there.
Also, I've created #918 for testing the simplified Ubuntu workflow definitions.

**Pull request merged**
