### PR TITLE
Check on all supported macOS versions

### PR DESCRIPTION
**Pull request by kelson42**
Better architecture and system coverage for macOS/iOS related CI

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr Do you know why a few macOS fail?

**Comment by mgautierfr** [comment]
Failling CI is crosscompiling from macos-13 to iOS.
Cross compiling use a "meson_cross_file" file found in https://tmp.kiwix.org/ci/deps2_osx_iOS_x86_64_libzim.tar.xz (step "Install Deps") generated by kiwix-build.
This file tells which compiler to use.

I **suppose** that this archive is build by kiwix-build for macos-12 and that the binaries paths have changed between macos-12 and macos-13

**Comment by kelson42** [comment]
OK, then I would create a dedicated ticket for that scenario and don't do it for the moment.

**Comment by kelson42** [comment]
@mgautierfr @rgaudin `macos-13-xlarge` (M1) keeps failing, but no log. Wonder what is going on here. Any idea?

**Comment by rgaudin** [comment]
We need units in our account ; that's in the logs

**Comment by rgaudin** [comment]
I don't recall exactly the message and I'm on my phone but it's something like that. M1 large are supposed to be in beta and free though

**Comment by kelson42** [comment]
@rgaudin I have commented-out the M1 testing as long as whole stuff is in beta. I'm not confortable to rely on an none-prod-ready service.

**Comment by kelson42** [comment]
We are almost good, do you know what trigger the 3 pending macos jobs?

**Pull request merged**
