### PR TITLE
Add support to recent googletest framework

### LINKED ISSUE #829: Unable to compile libzim in fresh Ubuntu 22.04
```
The Meson build system
Version: 0.61.2
Source dir: /home/kelson/code/libzim
Build dir: /home/kelson/code/libzim/build
Build type: native build
Project name: libzim
Project version: 8.2.1
C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking for size of "off_t" : 8
Checking for size of "size_t" : 8
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency liblzma found: YES 5.2.5
Run-time dependency libzstd found: YES 1.4.8
Run-time dependency xapian-core found: YES 1.4.18
Run-time dependency threads found: YES
Run-time dependency icu-i18n found: YES 70.1
Run-time dependency GTest found: YES (building self)
Configuring zim_config.h using configuration
Program libzim-compile-resources found: YES (/home/kelson/code/libzim/scripts/libzim-compile-resources)
Program download_test_data.py found: YES (/home/kelson/code/libzim/scripts/download_test_data.py)
Configuring config.h using configuration
Build targets in project: 33

Found ninja-1.10.1 at /usr/bin/ninja
ninja: Entering directory `build'
[1/191] Generating static/resources with a custom command
stopwords/af ['stopwords', 'af']
stopwords/ar ['stopwords', 'ar']
stopwords/bg ['stopwords', 'bg']
stopwords/bn ['stopwords', 'bn']
stopwords/br ['stopwords', 'br']
stopwords/ca ['stopwords', 'ca']
stopwords/cs ['stopwords', 'cs']
stopwords/da ['stopwords', 'da']
stopwords/de ['stopwords', 'de']
stopwords/el ['stopwords', 'el']
stopwords/en ['stopwords', 'en']
stopwords/eo ['stopwords', 'eo']
stopwords/es ['stopwords', 'es']
stopwords/et ['stopwords', 'et']
stopwords/eu ['stopwords', 'eu']
stopwords/fa ['stopwords', 'fa']
stopwords/fi ['stopwords', 'fi']
stopwords/fr ['stopwords', 'fr']
stopwords/ga ['stopwords', 'ga']
stopwords/gl ['stopwords', 'gl']
stopwords/gu ['stopwords', 'gu']
stopwords/ha ['stopwords', 'ha']
stopwords/he ['stopwords', 'he']
stopwords/hi ['stopwords', 'hi']
stopwords/hr ['stopwords', 'hr']
stopwords/hu ['stopwords', 'hu']
stopwords/hy ['stopwords', 'hy']
stopwords/id ['stopwords', 'id']
stopwords/it ['stopwords', 'it']
stopwords/ja ['stopwords', 'ja']
stopwords/ko ['stopwords', 'ko']
stopwords/ku ['stopwords', 'ku']
stopwords/la ['stopwords', 'la']
stopwords/lt ['stopwords', 'lt']
stopwords/lv ['stopwords', 'lv']
stopwords/mr ['stopwords', 'mr']
stopwords/ms ['stopwords', 'ms']
stopwords/nl ['stopwords', 'nl']
stopwords/no ['stopwords', 'no']
stopwords/pl ['stopwords', 'pl']
stopwords/pt ['stopwords', 'pt']
stopwords/ro ['stopwords', 'ro']
stopwords/ru ['stopwords', 'ru']
stopwords/sk ['stopwords', 'sk']
stopwords/sl ['stopwords', 'sl']
stopwords/so ['stopwords', 'so']
stopwords/st ['stopwords', 'st']
stopwords/sv ['stopwords', 'sv']
stopwords/sw ['stopwords', 'sw']
stopwords/th ['stopwords', 'th']
stopwords/tl ['stopwords', 'tl']
stopwords/tr ['stopwords', 'tr']
stopwords/uk ['stopwords', 'uk']
stopwords/ur ['stopwords', 'ur']
stopwords/vi ['stopwords', 'vi']
stopwords/yo ['stopwords', 'yo']
stopwords/zh ['stopwords', 'zh']
stopwords/zu ['stopwords', 'zu']
[64/191] Compiling C++ object test/error_in_creator.p/error_in_creator.cpp.o
FAILED: test/error_in_creator.p/error_in_creator.cpp.o 
c++ -Itest/error_in_creator.p -Iinclude -I../include -Isrc -I../src -I/usr/src/googletest/googletest -I/usr/src/googletest/googletest/include -fdiagnostics-color=always -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++17 -g -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -pthread -DWITH_TEST_DATA=1 -MD -MQ test/error_in_creator.p/error_in_creator.cpp.o -MF test/error_in_creator.p/error_in_creator.cpp.o.d -o test/error_in_creator.p/error_in_creator.cpp.o -c ../test/error_in_creator.cpp
In file included from /usr/src/googletest/googletest/include/gtest/gtest.h:67,
                 from ../test/error_in_creator.cpp:28:
/usr/src/googletest/googletest/include/gtest/gtest-param-test.h:500:38: error: ‘constexpr bool testing::internal::InstantiateTestCase_P_IsDeprecated()’ is deprecated: INSTANTIATE_TEST_CASE_P is deprecated, please use INSTANTIATE_TEST_SUITE_P [-Werror=deprecated-declarations]
  500 |   static_assert(::testing::internal::InstantiateTestCase_P_IsDeprecated(), \
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/googletest/googletest/include/gtest/gtest-param-test.h:500:38: note: in definition of macro ‘INSTANTIATE_TEST_CASE_P’
  500 |   static_assert(::testing::internal::InstantiateTestCase_P_IsDeprecated(), \
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/src/googletest/googletest/include/gtest/gtest.h:62,
                 from ../test/error_in_creator.cpp:28:
/usr/src/googletest/googletest/include/gtest/internal/gtest-internal.h:1297:16: note: declared here
 1297 | constexpr bool InstantiateTestCase_P_IsDeprecated() { return true; }
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/src/googletest/googletest/include/gtest/gtest.h:67,
                 from ../test/error_in_creator.cpp:28:
/usr/src/googletest/googletest/include/gtest/gtest-param-test.h:500:72: error: ‘constexpr bool testing::internal::InstantiateTestCase_P_IsDeprecated()’ is deprecated: INSTANTIATE_TEST_CASE_P is deprecated, please use INSTANTIATE_TEST_SUITE_P [-Werror=deprecated-declarations]
  500 |   static_assert(::testing::internal::InstantiateTestCase_P_IsDeprecated(), \
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
../test/error_in_creator.cpp:190:1: note: in expansion of macro ‘INSTANTIATE_TEST_CASE_P’
  190 | INSTANTIATE_TEST_CASE_P(
      | ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/src/googletest/googletest/include/gtest/gtest.h:62,
                 from ../test/error_in_creator.cpp:28:
/usr/src/googletest/googletest/include/gtest/internal/gtest-internal.h:1297:16: note: declared here
 1297 | constexpr bool InstantiateTestCase_P_IsDeprecated() { return true; }
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/src/googletest/googletest/include/gtest/gtest.h:67,
                 from ../test/error_in_creator.cpp:28:
/usr/src/googletest/googletest/include/gtest/gtest-param-test.h:500:38: error: ‘constexpr bool testing::internal::InstantiateTestCase_P_IsDeprecated()’ is deprecated: INSTANTIATE_TEST_CASE_P is deprecated, please use INSTANTIATE_TEST_SUITE_P [-Werror=deprecated-declarations]
  500 |   static_assert(::testing::internal::InstantiateTestCase_P_IsDeprecated(), \
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/googletest/googletest/include/gtest/gtest-param-test.h:500:38: note: in definition of macro ‘INSTANTIATE_TEST_CASE_P’
  500 |   static_assert(::testing::internal::InstantiateTestCase_P_IsDeprecated(), \
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/src/googletest/googletest/include/gtest/gtest.h:62,
                 from ../test/error_in_creator.cpp:28:
/usr/src/googletest/googletest/include/gtest/internal/gtest-internal.h:1297:16: note: declared here
 1297 | constexpr bool InstantiateTestCase_P_IsDeprecated() { return true; }
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/src/googletest/googletest/include/gtest/gtest.h:67,
                 from ../test/error_in_creator.cpp:28:
/usr/src/googletest/googletest/include/gtest/gtest-param-test.h:500:72: error: ‘constexpr bool testing::internal::InstantiateTestCase_P_IsDeprecated()’ is deprecated: INSTANTIATE_TEST_CASE_P is deprecated, please use INSTANTIATE_TEST_SUITE_P [-Werror=deprecated-declarations]
  500 |   static_assert(::testing::internal::InstantiateTestCase_P_IsDeprecated(), \
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
../test/error_in_creator.cpp:360:1: note: in expansion of macro ‘INSTANTIATE_TEST_CASE_P’
  360 | INSTANTIATE_TEST_CASE_P(
      | ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/src/googletest/googletest/include/gtest/gtest.h:62,
                 from ../test/error_in_creator.cpp:28:
/usr/src/googletest/googletest/include/gtest/internal/gtest-internal.h:1297:16: note: declared here
 1297 | constexpr bool InstantiateTestCase_P_IsDeprecated() { return true; }
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
[73/191] Compiling C++ object test/header.p/_usr_src_googletest_googletest_src_gtest-all.cc.o
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by kelson42**
Fixes #829

The questions left (I see at this time) are:
* Should we update subproject/gtest
* Does that not impair compilation on older distributions (in particular focal)

### CODE REVIEW

**Comment by mgautierfr** [comment]
`...TEST_CASE` is deprecated since [gtest 1.10.0](https://github.com/google/googletest/releases/tag/release-1.10.0) which was released in 2019.
We had 5 releases of gtest since (especially 1.13.0 for which we had to move to c++14/17).

> Does that not impair compilaation on older distributions (in particular focat)

Focal has gtest 1.10.0 so we are good here.


> Should we update subproject/gtest

Yes. (And also add a minimum version in meson.build)

**Comment by kelson42** [comment]
@mgautierfr Good, if OK for you, please just fix the last points and merge.

**Comment by kelson42** [comment]
@mgautierfr @legoktm Package `libgtest-dev` has version `1.8.1-3` on Debian Buster, see https://packages.debian.org/source/buster/googletest. But Buster Backports provides version `1.10.0` (which we need) see https://packages.debian.org/source/buster-backports/googletest. @legoktm There is no way you can also add the backport repository in the your Debian Buster Action?

**Comment by kelson42** [comment]
@mgautierfr Without feedback from @legoktm I propose to just comment-out or remove buster from the CI.

**Comment by legoktm** [comment]
Sorry for missing the ping earlier - let's just drop buster support entirely, it's no longer supported by Debian officially, just as part of Debian LTS.

**Comment by kelson42** [comment]
@mgautierfr I don't know why we have two linux CI failing because of libicu. Do you know? Can we merge?

**Pull request merged**
