### PR TITLE
add cirrus ci builds for FreeBSD

### PR DESCRIPTION
**Pull request by swills**
Currently broken due to a thread issue, I have a fix for that too.

### CODE REVIEW

**Comment by kelson42** [comment]
@swills Thank you for your PR, but why not usng Github action?

**Comment by swills** [comment]
Because GitHub Actions don't support FreeBSD.

**Comment by kelson42** [comment]
I'm a bit reluctant to add a dep to an other CI honestly...

**Comment by swills** [comment]
> I'm a bit reluctant to add a dep to an other CI honestly...

Can you elaborate on your concerns?

**Comment by kelson42** [comment]
@swills First of all, there should be no doubt about the fact that we want the libzim compiling/running smootly on FreeBSD. This is why, like always, I'm thankfull about your remarks and PRs. But, I want to consider carefully the maintenance costs, which implies:
* Complexity control
* Control about the dev process/tools
* Focus on the priority
* ...

If we add a CI it tends to:
* slow downs the CI
* Complexify it (fails more often)
* I have no control about the Cirrus CI
* I have no knowledge about the Cirrus CI
* I don't really understand if the compilation on FreeBSD is that different than on Linux
* FreeBSD is not part of our core portfolio of supported OSes.

So, basically, we have a lot of often questions. I don't want to oppose to this MR, but I would like to have all the cards in hand to be able to make a decision. Here are my questions:
* Is libzim compilation on FreeBSD going to always fail if we don't check early in the dev process (like in the CI)? If "yes" why?
* How Cirrus CI would integrate with Github (I don't see anything about it here in the visual report of the MR)?
* Who controls Cirrus CI for the libzim compilation? With wich account?
* Would not that be to virtualize FreeBSD on a Linux and run it on Github actions?
* Assuming we would add a FreeBSD in the libzim CI, who would be in charge of fixing things... I mean nobody has a FreeBSD at home. @swills Would you volunteer to fix whatever has to be fixed to suppport FreeBSD properly?

**Comment by swills** [comment]
> @swills First of all, there should be no doubt about the fact that we want the libzim compiling/running smootly on FreeBSD. This is why, like always, I'm thankfull about your remarks and PRs. But, I want to consider carefully the maintenance costs, which implies:
> 
>     * Complexity control
> 
>     * Control about the dev process/tools
> 
>     * Focus on the priority
> 
>     * ...
> 
> 

Sorry, I don't understand what this means.

> If we add a CI it tends to:
> 
>     * slow downs the CI
> 

Builds always take time, but they do happen in parallel so shouldn't take so long that it's a problem, based on what I've seen with other projects.

>     * Complexify it (fails more often)
> 

I tried the keep the job as simple as possible. What it does:

* starts a VM
* installs updates
* installs packages needed to build
* runs meson
* runs ninja

>     * I have no control about the Cirrus CI
> 

If this is merged, you'd have complete control of the Cirrus CI.

>     * I have no knowledge about the Cirrus CI
> 

You can take a look at this page:

https://cirrus-ci.org/guide/quick-start/

Once setup, I believe status would show up here:

https://cirrus-ci.com/github/openzim/libzim

It would also run the build and display the status and a link along with other checks in pull requests.

For example, take a look at another project which uses both GitHub and Cirrus:

https://github.com/Chatterino/chatterino2/pull/2268

The last check shows the cirrus-ci status.

>     * I don't really understand if the compilation on FreeBSD is that different than on Linux
> 

It's similar in some ways, different in others. It really depends on the details. Usually there aren't large issues.

>     * FreeBSD is not part of our core portfolio of supported OSes.
> 
> 

Ok, not sure what to say about this or how to respond to it.

> So, basically, we have a lot of often questions. I don't want to oppose to this MR, but I would like to have all the cards in hand to be able to make a decision. Here are my questions:
> 
>     * Is libzim compilation on FreeBSD going to always fail if we don't check early in the dev process (like in the CI)? If "yes" why?
> 

I'm not sure I understand this. Build failure happens regardless of when you check it. The goal is to catch issues when they're introduced, so that they're easier to fix, rather than later, when developers may have forgotten the change.

>     * How Cirrus CI would integrate with Github (I don't see anything about it here in the visual report of the MR)?
> 

See above.

>     * Who controls Cirrus CI for the libzim compilation? With wich account?
> 

See above.

>     * Would not that be to virtualize FreeBSD on a Linux and run it on Github actions?
> 

As far as I know, running FreeBSD binaries on Linux is not possible. Not sure if you're referring to a VM, but I don't think that would really allow usage of GitHub actions.

>     * Assuming we would add a FreeBSD in the libzim CI, who would be in charge of fixing things... I mean nobody has a FreeBSD at home. @swills Would you volunteer to fix whatever has to be fixed to suppport FreeBSD properly?

The goal is to find build failures when they're introduced, rather than after the fact. I'm happy to fix things to support FreeBSD.

Overall, you seem very apprehensive about this change, and I can't tell if it's related to Cirrus CI or FreeBSD or both.

Perhaps it's better to avoid it and continue fixing things after the fact, though that makes things much harder to fix.

**Pull request closed without merging**
