### PR TITLE
Bump-up version to 7.0.0

### PR DESCRIPTION
**Pull request by kelson42**

### CODE REVIEW

**Comment by legoktm** [comment]
Please also update the debian/ files for the version bump like I did in https://github.com/kiwix/kiwix-lib/pull/435

Also a comment on timing - Debian's "transition freeze" starts on Jan. 12, so if major version bumps are coming, if we can do it at least a few days before then so I can (try to) get them in for the next stable release (Debian 11/bullseye).

**Comment by kelson42** [comment]
@legoktm Thank you for the reminder. Concerning your invitation to release quickly, I'm not sure what would be the best. But considering that this is a massive change and the libzim6 has reached stability. I suspect this would not be reasonnable to push libzim7 just right before the freeze. @mgautierfr your opinion?

**Comment by kelson42** [comment]
@legoktm Wanted to merge this PR, but the deb packages somehow don't build. Any idea why?
```
 dh_missing: error: missing files, aborting
	 * dh_installdocs: libzim-dev (0), libzim7 (0)
```

**Comment by legoktm** [comment]
@kelson42 should be fixed now, we forgot to rename the `libzim6.install` file to `libzim7.install`.

**Comment by kelson42** [comment]
@legoktm merci

**Pull request merged**
