### PR TITLE
Added unit tests

### PR DESCRIPTION
**Pull request by MiguelRocha**
This PR adds unit tests for the following operations on zim::File:
   - getArticle
   - Iterators: begin(), beginByTitle, beginByUrl
   - find functions: byTitle, byUrl

It increases global libzim code coverage by 4.4%

### CODE REVIEW

**Comment by MiguelRocha** [comment]
@mgautierfr since the article was not found, do we really want to return a idx != 0 here: ?
https://github.com/openzim/libzim/blob/542e1e1e205ba3fca3b0145fb60a63ec0eb95dd4/src/fileimpl.cpp#L201

**Comment by mgautierfr** [comment]
> @mgautierfr since the article was not found, do we really want to return a idx != 0 here: ?

Yes. The functions `find` and `findByTitle` do not check for the bool and always return an article "closed" to the one searched.
This is, at least, used by kiwix to search suggestions starting by a prefix (https://github.com/kiwix/kiwix-lib/blob/master/src/reader.cpp#L734-L738).
And it may be used elsewhere.

I've made the same "mistake" already try to revamp a bit libzim.
As we plan to have a API break with #325 it may be also the time to thing about this and throw an exception if we cannot find an article and have the "soft" search in another function.

**Comment by MiguelRocha** [comment]
> > @mgautierfr since the article was not found, do we really want to return a idx != 0 here: ?
> 
> Yes. The functions `find` and `findByTitle` do not check for the bool and always return an article "closed" to the one searched.
> This is, at least, used by kiwix to search suggestions starting by a prefix (https://github.com/kiwix/kiwix-lib/blob/master/src/reader.cpp#L734-L738).
> And it may be used elsewhere.
> 
> I've made the same "mistake" already try to revamp a bit libzim.
> As we plan to have a API break with #325 it may be also the time to thing about this and throw an exception if we cannot find an article and have the "soft" search in another function.

Thank you for the clarification. I will take this into consideration in the tests.

I agree that we should have some way to tell the caller that the article was not found. And have the "soft" search in another function.

**Comment by mgautierfr** [comment]
This is good.

> I agree that we should have some way to tell the caller that the article was not found. And have the "soft" search in another function.

I just realize that we already have that. `getArticleBy*` return a "wrong" article if the article is not found. `findBy*` return a article "close" to the one searched.

**Pull request merged**
