### PR TITLE
Handling of large MIME-type list

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Fixes openzim/zim-tools#126

Unlike new-style ZIM archives created via libzim (where the first cluster is placed exactly at offset of 1024 bytes and the dirent pointer table is at the end of the archive), for old-style ZIM archives (where the dirent pointer table is placed immediately after the MIME-type list and before any clusters) there is no limit on the size of the MIME-type list. Though 944 (1024-*header_size*) bytes seemed to be a reasonable limit on the size of the MIME-type list, it turned out that at least one (old-style) ZIM file ([stackoverflow.com_en_all_2019-02.zim](https://download.kiwix.org/zim/stack_exchange/stackoverflow.com_en_all_2019-02.zim)) has been created violating that assumption (but, to be fair, it is likely due to a bug, since the MIME-type list in that file is a really weird one). Whatever, we better be able to open any ZIM files conforming to the
spec, and the spec doesn't impose any limits on the size of the MIME-type list.

The fix computes the likely upper limit on the end of the MIME-type list by checking only a few pointers in the ZIM archive:
- the offset of the dirent pointer table
- the offset of the title index table
- the offset of the cluster pointer table
- the offset of the first dirent
- the offset of the first cluster

It is assumed that the dirents and clusters are placed in the ZIM archive in ascending order (matching the order of the corresponding pointers in the respective tables).

Then the MIME-type list is loaded and parsed using a single buffer. This can be a problem for large corrupted ZIM archives, where all of the said pointers have very large values. Should we put a protection against such a case?

### CODE REVIEW

**Comment by veloman-yunkan** [comment]
I don't think that a separate validation check is required for the MIME-type list (as suggested by the discussion in #376). All the checking is done while loading the MIME-types in the `zim::Archive` constructor which is called by `zim::validate()`.

**Comment by mgautierfr** [comment]
> In its current form the PR breaks two unit-tests. How those failures should be fixed: by restoring the old functionality that was slightly against the spec or by "fixing" the content of the empty ZIM archive used in the unit tests?

There is always a mimetype list. If there is no mimetype, there is always the end `\0` (empty string).
So it seems that your commit is good. We should fix the empty zim archive of our test.

> I don't think that a separate validation check is required for the MIME-type list (as suggested by the discussion in #376). All the checking is done while loading the MIME-types in the zim::Archive constructor which is called by zim::validate().

There is something more to do. We have to ensure that all mimetype index in the dirents are valid (`<len(mimetypelist)` or redirect/deleted/target)

**Comment by veloman-yunkan** [comment]
> We should fix the empty zim archive of our test.

Done

> There is something more to do. We have to ensure that all mimetype index in the dirents are valid (`<len(mimetypelist)` or redirect/deleted/target)

This is a different type of a check. It validates the dirents rather than the MIME-type list. Let's do it in a separate PR 
(I unmarked #376 as being fixed by this PR).

**Comment by kelson42** [comment]
@mgautierfr Would you agree to approve/merge this branch?

**Comment by mgautierfr** [comment]
> Would you agree to approve/merge this branch?

I was waiting that CI passes.

We are good. Test on the mimetype index in the dirent still have to be made but we don't need it for this PR.

**Pull request merged**
