### PR TITLE
Fix default html parsing.

### PR DESCRIPTION
**Pull request by mgautierfr**
`countWord` was returning 1 for empty string.

This is a simple way to count word. But it is only use for statistic
about document. Actual count doesn't have to be exact.

### CODE REVIEW

**Comment by mgautierfr** [comment]
@kelson42 I'm not sure about the last commit.
It tells to not fulltext index the data if we have a tag `<meta name="robots" content="noindex">`. But this tag is for indexing robots (scrapper).
(I've writen the code before realizing I was maybe doing a bit too much here).

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

**Comment by kelson42** [comment]
> @kelson42 I'm not sure about the last commit.
> It tells to not fulltext index the data if we have a tag `<meta name="robots" content="noindex">`. But this tag is for indexing robots (scrapper).
> (I've writen the code before realizing I was maybe doing a bit too much here).

Yes, this is a content-based way to tell the ZIM creator to not index this HTML content. We should create an automated test for this behaviour. This abuses a bit the meta tag, but this offer the advantage to use a "standard" DOM node.

**Comment by mgautierfr** [comment]
> > @kelson42 I'm not sure about the last commit.
    It tells to not fulltext index the data if we have a tag <meta name="robots" content="noindex">. But this tag is for indexing robots (scrapper).
    (I've writen the code before realizing I was maybe doing a bit too much here).

> Yes, this is a content-based way to tell the ZIM creator to not index this HTML content. We should create an automated test for this behaviour. This abuses a bit the meta tag, but this offer the advantage to use a "standard" DOM node.

This is something I have added.
Before the test was simply `m_hasIndexData = (htmlParser.dump.find("NOINDEX") == std::string::npos);`
With the change I've made we have `_hasIndexData = !htmlParser.dump.empty() && htmlParser.indexing_allowed && (htmlParser.dump.find("NOINDEX") == std::string::npos);`

So we need a content to have indexData (an empty article will not be indexded), but we also check for the `htmlParser.indexing_allowed`. This bool correspond to the robots indexing and we were not using it before. I'm not sure it is a good thing to add.

**Review by kelson42 — APPROVED** [review]

**Comment by kelson42** [comment]
@mgautierfr Do you know if this fixes #519? Why has this PR been developed in a first place?

**Comment by mgautierfr** [comment]
> @mgautierfr Do you know if this fixes #519? Why has this PR been developed in a first place?

It was fixing your comment https://github.com/openzim/libzim/issues/519#issuecomment-793869447 in #519 but it is a different but that #519 itself.
It may also fix https://github.com/openzim/libzim/issues/481

The bug is pretty recent, it is a regression introduced with https://github.com/openzim/libzim/pull/511

**Comment by maneeshpm** [comment]
@mgautierfr  @kelson42 I can confirm that #481 gets fixed by this PR.

**Review by veloman-yunkan — APPROVED** [review]

**Comment by kelson42** [comment]
@mgautierfr There is still a codefactor error and the PR testing seems not good enough for codecov

**Comment by mgautierfr** [comment]
CodeFactor error has been fixed.
The low code coverage comes from the fact we reformat `myhtmlparse.cc`.
Without this change, the code coverage is 100% on the path and +3.06% for the whole project.

**Pull request merged**
