### PR TITLE
Change debian packaging version to 8.

### PR DESCRIPTION
**Pull request by mgautierfr**
This PR fix the debian packaging to move libzim version from 7 to 8.
And prepare version 8.0.1 release.

@legoktm please confirm that I've done what necessary. I'm not sure about the `(= ${binary:Version})`
It is (at least) necessary for release of zim-tools 3.1.2 which need new feature added in libzim 8 (see https://github.com/openzim/zim-tools/pull/321 CI)

### CODE REVIEW

**Comment by kelson42** [comment]
@legoktm Any feedback?

**Comment by kelson42** [comment]
@mgautierfr I guess we should merge this

**Comment by mgautierfr** [comment]
No. It doesn't help, so it is not a valid solution.

**Comment by kelson42** [comment]
We can not wait for weeks a feedback. Either there is one or we deal without. We should avoid at any price these PRs open during weeks or months.

**Comment by mgautierfr** [comment]
libzim 8.0.1 is made using this change. And it doesn't help other project CI.
See https://github.com/openzim/zim-tools/actions/runs/3009332969/jobs/4834181341 with especially this error message:
```
Broken zim-tools-build-deps:amd64 Depends on libzim-dev:amd64 < none | 7.2.2~focal @un uH > (>= 8.0.0~)
  Removing zim-tools-build-deps:amd64 because I can't find libzim-dev:amd64
```
If we cannot wait for feedback we have to do the job ourselves to understand debian packaging and how @legoktm made this on openzim CI. But we must not merge something we know it doesn't help us.

**Pull request merged**
