### PR TITLE
fix:vcpkg build issue

### PR DESCRIPTION
**Pull request by xiaoyifang**
try to support both static and dynamic library on Windows

related to #741

### CODE REVIEW

**Comment by mgautierfr** [comment]
Can you explain a bit more what was wrong and how it solves the issue ?

- Setting `LIBZIM_EXPORT_DLL` in the conf doesn't work ?
- Setting it even on non windows builds break something ?
- Why moving it a a `-D` flags only on windows ?

**Comment by xiaoyifang** [comment]
> Can you explain a bit more what was wrong and how it solves the issue ?
> 
> * Setting `LIBZIM_EXPORT_DLL` in the conf doesn't work ?

Yes ,it does not work.

> * Setting it even on non windows builds break something ?
> * Why moving it a a `-D` flags only on windows ?

It only needed on Windows, other platforms do not have the build issue,  This will make the affected range at minimum.
https://github.com/mesonbuild/meson/issues/7838

**Comment by mgautierfr** [comment]
Yes, but why it doesn't work ? (And so, why your fix makes things work ?)

**Comment by xiaoyifang** [comment]
```

#define VERSION "8.2.0"

#define DIRENT_CACHE_SIZE 512

#define DIRENT_LOOKUP_CACHE_SIZE 1024

#define CLUSTER_CACHE_SIZE 16

#define LZMA_MEMORY_SIZE 128

#undef ENABLE_XAPIAN

#undef ENABLE_USE_MMAP

#define ENABLE_USE_BUFFER_HEADER

#define MMAP_SUPPORT_64 0

#define ENV64BIT 1

#define ENV32BIT 0

```

**Comment by mgautierfr** [comment]
It should be better to add it in the `config.h.in` if it fixes things.
It will be more consistent with the other defines (and so easier to maintain)

**Comment by xiaoyifang** [comment]
the example failed,  I do not think it was caused by my PR.

**Comment by xiaoyifang** [comment]
win32_dyn example compiled error,is it caused by this PR?

**Comment by kelson42** [comment]
> win32_dyn example compiled error,is it caused by this PR?

pretty sure

**Comment by xiaoyifang** [comment]
```
/usr/lib/gcc/i686-w64-mingw32/11.2.1/../../../../i686-w64-mingw32/bin/ld: examples/createZimExample.exe.p/createZimExample.cpp.obj: in function `ZN3zim6writer14StringProviderC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
/__w/libzim/libzim/build/../include/zim/writer/contentProvider.h:94: undefined reference to `vtable for zim::writer::StringProvider'
/usr/lib/gcc/i686-w64-mingw32/11.2.1/../../../../i686-w64-mingw32/bin/ld: examples/createZimExample.exe.p/createZimExample.cpp.obj: in function `ZN3zim6writer4ItemC2Ev':
/__w/libzim/libzim/build/../include/zim/writer/item.h:127: undefined reference to `vtable for zim::writer::Item'
/usr/lib/gcc/i686-w64-mingw32/11.2.1/../../../../i686-w64-mingw32/bin/ld: examples/createZimExample.exe.p/createZimExample.cpp.obj: in function `ZN3zim6writer4ItemD2Ev':
/__w/libzim/libzim/build/../include/zim/writer/item.h:[224](https://github.com/openzim/libzim/actions/runs/4948322467/jobs/8848883260?pr=792#step:5:225): undefined reference to `vtable for zim::writer::Item'
/usr/lib/gcc/i686-w64-mingw32/11.2.1/../../../../i686-w64-mingw32/bin/ld: examples/createZimExample.exe.p/createZimExample.cpp.obj:createZimExample.cpp:(.rdata$_ZTV8TestItem[__ZTV8TestItem]+0x18): undefined reference to `zim::writer::Item::getIndexData() const'
/usr/lib/gcc/i686-w64-mingw32/11.2.1/../../../../i686-w64-mingw32/bin/ld: examples/createZimExample.exe.p/createZimExample.cpp.obj:createZimExample.cpp:(.rdata$_ZTV8TestItem[__ZTV8TestItem]+0x1c): undefined reference to `zim::writer::Item::getHints() const'
```

LIBZIM_API  is defined on the following condition .  should I check MINGW too?

```
#if (defined _WIN32 || defined __CYGWIN__) && defined LIBZIM_EXPORT_DLL
    #define LIBZIM_API __declspec(dllexport)
#else
    #define LIBZIM_API
#endif
```

**Comment by mgautierfr** [comment]
You can use `#pragma message("foo")`to be sure that the define is correct (see https://learn.microsoft.com/fr-fr/cpp/preprocessor/message?view=msvc-170)

**Comment by xiaoyifang** [comment]
image

I have followed this instruction ,but seems put dll(export) on class is not sufficient.  some class's methods are not export to dll at all.

**Comment by mgautierfr** [comment]
Do you have a link to the documentation ?

**Comment by xiaoyifang** [comment]
https://learn.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-declspec-dllexport?view=msvc-170

**Comment by xiaoyifang** [comment]
superceded by #796

**Pull request closed without merging**
