### PR TITLE
Search iterator should be made camelcase

### LINKED ISSUE #562: Move search iterator API to camelCase.
libzim use camelCase api, search iterator should follow this convention (`getTitle` instead of `get_title`)

### PR DESCRIPTION
**Pull request by maneeshpm**
Fixes #562 

Changes included in this pr:
- Move the search iterator API to use camel case 
- Fix libzim internally to use this new scheme

### CODE REVIEW

**Comment by kelson42** [comment]
Putting @veloman-yunkan as reviewer as I fell uncofortable to validate this PR myself. To me looks good.

**Review by veloman-yunkan — COMMENTED** [review]
Merging this PR will break the libkiwix CI again. The old names can be temporarily retained, and will be removed after libkiwix is updated. Of course this is a slightly slower procedure, but at least it doesn't break things.

**Comment by kelson42** [comment]
@veloman-yunkan I'm not against this last idea, but considering that libkiwix10 breaks things anyway strongly, this seems not necessary.

**Comment by maneeshpm** [comment]
@kelson42 I can have a PR ready on libkiwix as well so that we can better plan the merge such that the CI downtime is minimal. But yes, as @veloman-yunkan mentioned this is not very urgent and we can hold it back until some major libkiwix update like a fix for kiwix/libkiwix#430 is ready.

**Comment by kelson42** [comment]
@maneeshpm Please prepare the PRs for zim-tools and libkiwix, so we can at least secure these two projects will continue to compile properly.

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan I'm not against this last idea, but considering that libkiwix10 breaks things anyway strongly, this seems not necessary.

I was more concerned with disruption to the development process, similar to the one that happened during the last change to the libzim search API.

**Comment by mgautierfr** [comment]
The python wrapper must also be updated. (But it is already broken, https://github.com/openzim/python-libzim/issues/109, we can update python-libzim all at once).

If the two PR kiwix/libkiwix#537 and openzim/zim-tools#245 are ok (I've reviewed them and it is ok on my side) I think we can merge this PR and the two other the day after.

> and we can hold it back until some major libkiwix update like a fix for kiwix/libkiwix#430 is ready.

I'm not in favor of blocking a project because of another development in another project.

**Review by mgautierfr — APPROVED** [review]

**Comment by maneeshpm** [comment]
@mgautierfr I have opened the other two PRs. I have just rebased and requested your review there, no change in code.

**Pull request merged**
